version: '3.8'
services:
  neo4j:
    image: neo4j:5.17
    container_name: neo4j-arm
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/Siraff.09"
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/import
      - ./plugins:/plugins
